In [1]:
import pandas as pd 
import numpy as np
import category_encoders as ce



In [2]:
data=pd.DataFrame({'height':['Low','Medium','High','Low','Medium','High','Low','Medium','High'],
                  'name':  ['Razan','Atheer','Norah','Mohammed','Razan','Atheer','Mohammed','layla','Mohammed'],
                  'Month': ['January','April','March','April','Februay','June','July','June','September']
                 })

# Q1: Apply Ordinal encoding.

## global variable

In [3]:
from sklearn.preprocessing import OrdinalEncoder
#ord1 = OrdinalEncoder()

encoder= ce.OrdinalEncoder(cols=['height'],return_df=True,mapping=[{'col':'height','mapping':{'None':0,'High':1,'Medium':2,'Low':3}}])

# transforming the column after fitting
data["height"] = encoder.fit_transform(data[["height"]])

data.head(10)


height      name      Month
0       3     Razan    January
1       2    Atheer      April
2       1     Norah      March
3       3  Mohammed      April
4       2     Razan    Februay
5       1    Atheer       June
6       3  Mohammed       July
7       2     layla       June
8       1  Mohammed  September

## local variable

- I did not specify the values

In [4]:
from sklearn.preprocessing import OrdinalEncoder

dataOrdinalEncoding=pd.DataFrame({'height':['Low','Medium','High','Low','Medium','High','Low','Medium','High',]})
# define ordinal encoding
encoder = OrdinalEncoder()
# transform data
dataOrdinalEncoding['Ordinal'] = encoder.fit_transform(dataOrdinalEncoding)
print(dataOrdinalEncoding)


   height  Ordinal
0     Low      1.0
1  Medium      2.0
2    High      0.0
3     Low      1.0
4  Medium      2.0
5    High      0.0
6     Low      1.0
7  Medium      2.0
8    High      0.0


- I  specify the values

In [5]:
df=pd.DataFrame({'height':['Low','Medium','High','Low','Medium','High','Low','Medium','High',]})

# create object of Ordinalencoding
encoder= ce.OrdinalEncoder(cols=['height'],return_df=True,mapping=[{'col':'height','mapping':{'None':0,'High':1,'Medium':2,'Low':3}}])

df['transformed'] = encoder.fit_transform(df)

print(df)


   height  transformed
0     Low            3
1  Medium            2
2    High            1
3     Low            3
4  Medium            2
5    High            1
6     Low            3
7  Medium            2
8    High            1


# Q2: Apply One hot encoding.

## global variable

In [6]:
from sklearn.preprocessing import OneHotEncoder

# define one hot encoding
encoder= OneHotEncoder()

encoder = encoder.fit_transform(data[['name']]).toarray()
# converting arrays to a dataframe
encoded_colm = pd.DataFrame(encoder)

# concatenating dataframes
data = pd.concat([data, encoded_colm], axis=1)

# removing the encoded column.
#data = data.drop(['name'], axis=1)

data.head(10)


height      name      Month    0    1    2    3    4
0       3     Razan    January  0.0  0.0  0.0  1.0  0.0
1       2    Atheer      April  1.0  0.0  0.0  0.0  0.0
2       1     Norah      March  0.0  0.0  1.0  0.0  0.0
3       3  Mohammed      April  0.0  1.0  0.0  0.0  0.0
4       2     Razan    Februay  0.0  0.0  0.0  1.0  0.0
5       1    Atheer       June  1.0  0.0  0.0  0.0  0.0
6       3  Mohammed       July  0.0  1.0  0.0  0.0  0.0
7       2     layla       June  0.0  0.0  0.0  0.0  1.0
8       1  Mohammed  September  0.0  1.0  0.0  0.0  0.0

## local variable

In [7]:
from sklearn.preprocessing import OneHotEncoder
# define data
dataOneHot=pd.DataFrame({'name':[
'Razan','Atheer','Norah','Mohammed','Razan','Atheer','Mohammed'
]})

# define one hot encoding
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(dataOneHot)
print(onehot)

[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


# Q3: Apply Frequency Encoding. 

## global variable

In [8]:
# grouping by frequency
df = data.groupby('name').size()/len(df)

# mapping values to dataframe
data.loc[:, "name_freq_encode"] = data['name'].map(df)

# drop original column.
#data = data.drop(['nom_0'], axis=1)

data.head(10)


height      name      Month    0    1    2    3    4  name_freq_encode
0       3     Razan    January  0.0  0.0  0.0  1.0  0.0          0.222222
1       2    Atheer      April  1.0  0.0  0.0  0.0  0.0          0.222222
2       1     Norah      March  0.0  0.0  1.0  0.0  0.0          0.111111
3       3  Mohammed      April  0.0  1.0  0.0  0.0  0.0          0.333333
4       2     Razan    Februay  0.0  0.0  0.0  1.0  0.0          0.222222
5       1    Atheer       June  1.0  0.0  0.0  0.0  0.0          0.222222
6       3  Mohammed       July  0.0  1.0  0.0  0.0  0.0          0.333333
7       2     layla       June  0.0  0.0  0.0  0.0  1.0          0.111111
8       1  Mohammed  September  0.0  1.0  0.0  0.0  0.0          0.333333

## local variable

In [9]:
from sklearn.preprocessing import LabelEncoder 

dataFrequency=pd.DataFrame({'name':[
'Razan','Atheer','Norah','Mohammed','Razan','Atheer','Mohammed'
]})

le = LabelEncoder()
dataFrequency['Frequency'] = le.fit_transform(dataFrequency['name'])


print(dataFrequency)

       name  Frequency
0     Razan          3
1    Atheer          0
2     Norah          2
3  Mohammed          1
4     Razan          3
5    Atheer          0
6  Mohammed          1


# Q4: Apply Binary Encoding. 

## global variable

In [10]:
from category_encoders import BinaryEncoder

encoder = BinaryEncoder(cols =['Month'])

# transforming the column after fitting
newdata = encoder.fit_transform(data['Month'])

# concatenating dataframe
data = pd.concat([data, newdata], axis = 1)

# dropping old column
#df = df.drop(['ord_2'], axis = 1)
data.head(10)

height      name      Month    0    1    2    3    4  name_freq_encode  \
0       3     Razan    January  0.0  0.0  0.0  1.0  0.0          0.222222   
1       2    Atheer      April  1.0  0.0  0.0  0.0  0.0          0.222222   
2       1     Norah      March  0.0  0.0  1.0  0.0  0.0          0.111111   
3       3  Mohammed      April  0.0  1.0  0.0  0.0  0.0          0.333333   
4       2     Razan    Februay  0.0  0.0  0.0  1.0  0.0          0.222222   
5       1    Atheer       June  1.0  0.0  0.0  0.0  0.0          0.222222   
6       3  Mohammed       July  0.0  1.0  0.0  0.0  0.0          0.333333   
7       2     layla       June  0.0  0.0  0.0  0.0  1.0          0.111111   
8       1  Mohammed  September  0.0  1.0  0.0  0.0  0.0          0.333333   

   Month_0  Month_1  Month_2  
0        0        0        1  
1        0        1        0  
2        0        1        1  
3        0        1        0  
4        1        0        0  
5        1        0        1  
6        1        1        0  
7        1        0        1  
8        1        1        1

## local variable

In [11]:
dataBinary=pd.DataFrame({'Month':['January','April','March','April','Februay','June','July','June','September']})
encoder= ce.BinaryEncoder(cols=['Month'],return_df=True)
Binary=encoder.fit_transform(dataBinary) 
Binary

Month_0  Month_1  Month_2
0        0        0        1
1        0        1        0
2        0        1        1
3        0        1        0
4        1        0        0
5        1        0        1
6        1        1        0
7        1        0        1
8        1        1        1