In [14]:
import pandas as pd 
import numpy as np
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
!pip install category_encoders
import category_encoders as ce

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 418.4 kB/s eta 0:00:00a 0:00:01


# Q1: Apply Ordinal encoding.

In [2]:
# define data

data = {'ID': [1, 2, 3,4,5],
        'Grade': ['A+', 'B+', 'C+','D+','F'],
       }
df=pd.DataFrame(data, columns=['ID','Grade'])
df

ID Grade
0   1    A+
1   2    B+
2   3    C+
3   4    D+
4   5     F

In [3]:
# define ordinal encoding
encoder = OrdinalEncoder()
# transform data
result = encoder.fit_transform(df)
print(result)

[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]]


# Q2: Apply One hot encoding.

In [4]:
# define data
data2 = {'ID': [1, 2, 3],
        'Color': ['Red', 'Green', 'Blue'],
       }
df2=pd.DataFrame(data2, columns=['ID','Color'])
df2

ID  Color
0   1    Red
1   2  Green
2   3   Blue

In [9]:
# define one hot encoding
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(df2[['Color']])
print(onehot)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


#### other solution by array

In [10]:
from numpy import asarray
# define data
data = asarray([['Red'], ['Green'], ['Blue']])
# define one hot encoding
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)


[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


# Q3: Apply Frequency Encoding. 

In [19]:
df['Freq encode'] = ce.CountEncoder(cols=['Grade']).fit(df).transform(df)['Grade']
df['Freq encode']

0    1
1    1
2    1
3    1
4    1
Name: Freq encode, dtype: int64

# Q4: Apply Binary Encoding. 

In [29]:
DataBinary=pd.DataFrame({'Days':['Sun','Mon','Tues','Wed','Thurs','Fri','Sat']})
encoder= ce.BinaryEncoder(cols=['Days'],return_df=True)
Binary=encoder.fit_transform(DataBinary) 
Binary


Days_0  Days_1  Days_2
0       0       0       1
1       0       1       0
2       0       1       1
3       1       0       0
4       1       0       1
5       1       1       0
6       1       1       1