In [1]:
import pandas as pd 
import numpy as np

# Q1: Apply Ordinal encoding.

In [2]:
from sklearn.preprocessing import OrdinalEncoder

OrdEnc = OrdinalEncoder()
Data = [['Excellent', 5],['Very Good', 6],['Good', 4],['Accepted', 10], ['Bad', 3], ['Very Good', 12]]

OrdEnc.fit(Data)

OrdinalEncoder()

In [3]:
OrdEnc.categories_

[array(['Accepted', 'Bad', 'Excellent', 'Good', 'Very Good'], dtype=object),
 array([3, 4, 5, 6, 10, 12], dtype=object)]

In [4]:
OrdEnc.fit_transform(Data)

array([[2., 2.],
       [4., 3.],
       [3., 1.],
       [0., 4.],
       [1., 0.],
       [4., 5.]])

# Q2: Apply One hot encoding.

In [5]:
from sklearn.preprocessing import OneHotEncoder
OneHotEnc = OneHotEncoder()

OneHotEnc.fit(Data)

OneHotEncoder()

In [6]:
OneHotEnc.categories_

[array(['Accepted', 'Bad', 'Excellent', 'Good', 'Very Good'], dtype=object),
 array([3, 4, 5, 6, 10, 12], dtype=object)]

In [7]:
OneHotEnc.transform(Data).toarray()

array([[0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [8]:
OneHotEnc.inverse_transform([[0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.]])

array([['Excellent', 5],
       ['Very Good', 6],
       ['Good', 4],
       ['Accepted', 10],
       ['Bad', 3],
       ['Very Good', 12]], dtype=object)

# Q3: Apply Frequency Encoding. 

In [89]:
import random
import collections
Datalist = ['Excellent', 'Very Good', 'Good', 'Accepted', 'Bad']*100

Datalist = random.sample(Datalist, 80)
DatalistFreq = collections.Counter(Datalist)
DatalistFreq = dict(DatalistFreq)
DatalistFreqFinal = pd.DataFrame.from_dict(DatalistFreq, orient='index', columns=['Freq'])

In [90]:
DatalistFreqFinal

Freq
Good         10
Accepted     18
Very Good    21
Bad          15
Excellent    16

# Q4: Apply Binary Encoding. 

In [99]:
from sklearn.preprocessing import LabelEncoder, LabelBinarizer
import math

Datalist = ['Excellent', 'Very Good', 'Good', 'Accepted', 'Bad']*2

DataBinaryDF = pd.DataFrame(Datalist, columns=['Grade'])
DataBinaryDF

Grade
0  Excellent
1  Very Good
2       Good
3   Accepted
4        Bad
5  Excellent
6  Very Good
7       Good
8   Accepted
9        Bad

In [100]:
LabelEnc = LabelEncoder()
LabelEnc.fit(Datalist)

LabelEncoder()

In [101]:
LabelEnc.classes_

array(['Accepted', 'Bad', 'Excellent', 'Good', 'Very Good'], dtype='<U9')

In [102]:
DataNumCate = LabelEnc.fit_transform(Datalist)
DataNumCate

array([2, 4, 3, 0, 1, 2, 4, 3, 0, 1], dtype=int64)

In [103]:
DataBinaryDF['CatLabel'] = DataNumCate

In [104]:
DataBinaryDF

Grade  CatLabel
0  Excellent         2
1  Very Good         4
2       Good         3
3   Accepted         0
4        Bad         1
5  Excellent         2
6  Very Good         4
7       Good         3
8   Accepted         0
9        Bad         1

In [82]:
def DecimalToBinary(Num, NumOfDigit):
    List = []
    
    for i  in range(NumOfDigit):
         List.append(0)
            
    Binary = 0
    
    if Num == 0:
        pass
    
    i = -1
    while(Num > 0):
        Binary = (Num%2)
        List[i] = Binary
        Num = int(Num/2)
        i -= 1
    return List

In [83]:
NumList = [int(x) for x in DataNumCate]
MaxVal = max(NumList)
NumOfDigits = math.log(MaxVal,2)+1
NumOfDigits

3.0

In [86]:
AllNum = []
for Category in NumList: 
    AllNum.append(DecimalToBinary(int(Category), int(NumOfDigits)))
AllNum

[[0, 1, 0],
 [1, 0, 0],
 [0, 1, 1],
 [0, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [1, 0, 0],
 [0, 1, 1],
 [0, 0, 0],
 [0, 0, 1]]

In [97]:
DF = pd.DataFrame(AllNum, columns=['D1','D2','D3'])
DF

D1  D2  D3
0   0   1   0
1   1   0   0
2   0   1   1
3   0   0   0
4   0   0   1
5   0   1   0
6   1   0   0
7   0   1   1
8   0   0   0
9   0   0   1

In [105]:
DataBinaryDF.join(DF)

Grade  CatLabel  D1  D2  D3
0  Excellent         2   0   1   0
1  Very Good         4   1   0   0
2       Good         3   0   1   1
3   Accepted         0   0   0   0
4        Bad         1   0   0   1
5  Excellent         2   0   1   0
6  Very Good         4   1   0   0
7       Good         3   0   1   1
8   Accepted         0   0   0   0
9        Bad         1   0   0   1